@startuml MainUseCase
left to right direction
skinparam packageStyle rectangle

actor Мастер
actor Заказчик

Мастер --> (Регистрация в системе)
Мастер --> (Настройка стиля экспорта)
Мастер --> (Добавление типовых видов работ и их стоимости)
(Добавление типовых видов работ и их стоимости) -.> (Просмотр списка типовых видов работ и их стоимости) : "include"

Мастер --> (Создание, изменение и удаление проекта)
(Создание, изменение и удаление проекта) -.> (Просмотр списка проектов) : "include"

rectangle Проект {
    Мастер --> (Регистрация заказчика\nв рамках проекта)
    Мастер --> (Добавление объекта)
    Мастер --> (Просмотр списка объектов)
    Мастер --> (Редактирование объекта)
    Мастер --> (Добавление сметы)
    Мастер --> (Редактирование сметы)
    Мастер --> (Отправка pdf файла\nсметы на контакт заказчика)
    Мастер --> (Скачивание pdf файла сметы)
    Мастер --> (Генерация открытой ссылки на смету\nпо контакту заказчика)
    Мастер --> (Просмотр списка смет)
    Заказчик --> (Подтверждение сметы)
    Заказчик --> (Добавление комментариев к смете)

    (Регистрация заказчика\nв рамках проекта) -.> (Просмотр проекта и его деталей) : "include"
    (Добавление объекта) -.> (Просмотр проекта и его деталей) : "include"
    (Редактирование объекта) -.> (Просмотр проекта и его деталей) : "include"
    (Добавление сметы) -.> (Просмотр проекта и его деталей) : "include"
    (Просмотр списка смет) -.> (Просмотр проекта и его деталей) : "include"
    (Просмотр списка объектов) -.> (Просмотр проекта и его деталей) : "include"
    (Редактирование сметы) -.> (Просмотр сметы и\n её комментариев) : "include"
    (Подтверждение сметы) -.> (Просмотр сметы и\n её комментариев) : "include"
    (Добавление комментариев к смете) -.> (Просмотр сметы и\n её комментариев) : "include"
    (Скачивание pdf файла сметы) -.> (Просмотр сметы и\n её комментариев) : "include"
    (Отправка pdf файла\nсметы на контакт заказчика) -.> (Просмотр сметы и\n её комментариев) : "include"
    (Генерация открытой ссылки на смету\nпо контакту заказчика) -.> (Просмотр сметы и\n её комментариев) : "include"

    (Отправка pdf файла\nсметы на контакт заказчика) -.> (Генерация pdf файла сметы) : "include"
    (Скачивание pdf файла сметы) -.> (Генерация pdf файла сметы) : "include"
}
@enduml